name: CI

on: [push, pull_request]

jobs:
  ci:
    uses: lalalili/.github/.github/workflows/php-package-ci.yml@main
    secrets: inherit
    with:
      php-versions: "['8.4']"
      laravel-versions: "['13.*']"
      run-analyse: true
      run-format: true
